runtime: python39

entrypoint: gunicorn -b :$PORT "app:create_app()"

handlers:
  - url: /
    static_files: dist/client/index.html
    upload: dist/client/index.html

  - url: /api/.*
    script: auto

  - url: /(.*\.js)
    static_files: dist/client/\1
    upload: dist/client/.*\.js

  - url: /(.*\.css)
    static_files: dist/client/\1
    upload: dist/client/.*\.css

  - url: /(.*\.woff)
    static_files: dist/client/\1
    upload: dist/client/.*\.woff

  - url: /(.*)
    static_files: dist/client/index.html
    upload: dist/client/(.*)
